Algoritmo "Perguntas"

Var

   idade : inteiro
   trab: caractere
   salario : real
   

Inicio

   escreva("Quantos anos você tem? ")
   leia(idade)
   escreval("Nossa, você só tem ", idade, ", nem parece!")
   escreval("E você faz o que da vida?")
   leia(trab)
   escreval("Parece ser uma função bem importante, o salário é bom?")
   leia(salario)
   escreval("Então, você é ", trab, ", ganha ", salario:8:2, " e só tem ", idade, "? Ta bom de mais")

Fimalgoritmo